// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace PJNMGamplayTags
{
	/** input Tags **/
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Zoom)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Action) 

	/** Player Weapon Tags **/
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Primary)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Primary_Equipped)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Secondary) 
}