// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace PJNMGamplayTags
{
	/** input Tags **/
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Zoom)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Action) 
	
	/** Player Weapon Tags **/
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Primary)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Primary_Equipped)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Secondary)

	/** Player Weapon Class **/
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Class_Rifle)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Class_SMG)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Class_DMR)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Class_Sniper)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Class_Shotgun)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Class_Pistol)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Class_Knife)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Class_Equipment)

	/** Unique Weapon Class **/
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_ID_AK74)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_ID_Glock18)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_ID_M4)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_ID_M1911)
	PJNIGHTMARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_ID_Knife)
}